### PR TITLE
RA-1387:Upgrade FontAwesome from 3.x to latest (5+) (for uicommons)

### PR DESCRIPTION
**Pull request by haripriya999**
# RA-1387:Upgrade FontAwesome from 3.x to latest (5+)

## Description of what I changed
Upgraded font awesome to latest 5.9.0 to support a wider set of icons (for uicommons)

## Issue I worked on

see https://issues.openmrs.org/browse/RA-1387

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@haripriya999 i have tested your work but do not see any changes to the icons listed here? https://demo.openmrs.org/openmrs/uicommons/icons.page

**Comment by haripriya999** [comment]
> @haripriya999 i have tested your work but do not see any changes to the icons listed here? https://demo.openmrs.org/openmrs/uicommons/icons.page

@dkayiwa  The icons listed here are of font awesome 3. I didn't know we had this page to display icons. In this PR i just upgraded font awesome to 5.9.0 and tested it by replacing a few old icons with the newly defined one's, and it worked. I didn't write code to display the font awesome 5 icons list in this page. Should I list them over here ?

**Comment by dkayiwa** [comment]
Yes go ahead.

**Comment by haripriya999** [comment]
@dkayiwa  Its throwing this error on browser while trying to display all icons (around 1630 icons) of fontawesome 5: https://pastebin.com/qB2SWAu3 , but its working fine when I cut down the icons to be displayed. 
How many icons do you think we must display?

**Comment by dkayiwa** [comment]
All of them.

**Comment by haripriya999** [comment]
> All of them.

It's throwing error when I try to display all of them.

**Comment by haripriya999** [comment]
I updated the PR to show around 600 icons. Its failing to load page when I try to add beyond it.

**Comment by haripriya999** [comment]
@dkayiwa  can you take a look at this?

**Comment by dkayiwa** [comment]
Did you resolve the errors?

**Comment by haripriya999** [comment]
This PR displays around 600 icons without any error while loading.

**Comment by dkayiwa** [comment]
Can you share, on the ticket, a screenshot of the style guide page with these icons? Like here: https://demo.openmrs.org/openmrs/uicommons/styleGuide.page

**Comment by haripriya999** [comment]
> Can you share, on the ticket, a screenshot of the style guide page with these icons? Like here: https://demo.openmrs.org/openmrs/uicommons/styleGuide.page

@dkayiwa I updated the screenshots

**Comment by dkayiwa** [comment]
So what was causing the problem?

**Comment by haripriya999** [comment]
The string length was exceeding 65535 unicode units, which is the maximum string length jvm can handle.

**Comment by dkayiwa** [comment]
So how did you deal with it?

**Comment by haripriya999** [comment]
> So how did you deal with it?

I displayed 600 icons of the whole so that the string length doesn't exceed the maximum.

**Comment by dkayiwa** [comment]
And you left out how many?

**Comment by haripriya999** [comment]
> And you left out how many?

between 900-1000 , I also tried loading them as different elements, but that didn't work.

**Comment by dkayiwa** [comment]
Can you share the error message which you based on to conclude that it was a problem with the string length?

**Comment by haripriya999** [comment]
> Can you share the error message which you based on to conclude that it was a problem with the string length?

Error message:  https://pastebin.com/qB2SWAu3

**Comment by dkayiwa** [comment]
What is the exact file from which you are cutting down on the number of icons?

**Comment by haripriya999** [comment]
> What is the exact file from which you are cutting down on the number of icons?

I was doing that here: https://github.com/openmrs/openmrs-module-uicommons/blob/master/omod/src/main/webapp/pages/icons.gsp . I updated the PR and it's now working. Also updated the screenshots on ticket.

**Comment by dkayiwa** [comment]
@haripriya999 what did you do differently this time?

**Comment by haripriya999** [comment]
> @haripriya999 what did you do differently this time, to make it work?

I defined 4 strings and put the html in them.

**Comment by dkayiwa** [comment]
Which ones are they?

**Comment by haripriya999** [comment]
> Which ones are they?

fontAwesomeIconSet1,fontAwesomeIconSet2,fontAwesomeIconSet3,fontAwesomeIconSet4 defined in icons.gsp

**Pull request merged**
