### PR TITLE
UICM-93: Bootstrap datetimepicker 'es' locale file + date parsing fix.

### PR DESCRIPTION
**Pull request by VasanthakumarTW**
UICM-93: Added Bootstrap Datetimepicker spanish (es) locale file and fixed the parse error for all assigned date values

### CODE REVIEW

**Comment by VasanthakumarTW** [comment]
@mks-d - Please review this

**Comment by mks-d** [comment]
@mogoodrich I think @VasanthakumarTW is probably backporting a fix that came from more recent versions of Bootstrap's datetime picker to make it work in 'es'.

@VasanthakumarTW can you remind us why not simply upgrading the datetime picker altogether?

**Comment by VasanthakumarTW** [comment]
@mogoodrich - Based on OpenMRS talk (https://talk.openmrs.org/t/html-form-entry-use-obsfromfragment-datetimepicker-value-as-encounter-datetime/26259), we have modified the existing library.

@mks-d - Since upgradation of BootStrap library will lead all OpenMRS users to test and change their parameters based on new version. For eg: OpenMRS uicommons - datetimepicker fragment needs to go with lot of parameter changes. And also there are UI changes compared to latest version and version we are using. For safer fallback, this is an option and in future we can introduce new fragment with latest  bootstrap version for usage.

**Comment by mogoodrich** [comment]
Thanks @VasanthakumarTW , works for me!

**Comment by VasanthakumarTW** [comment]
@mks-d - Please approve this PR. It is not allowing me to add reviewer.

**Comment by mogoodrich** [comment]
Actually, reading this a little closer now... we are using our own custom hack of bootstrap?  That does seem risky.  It is possible to upgrade to a version of bootstrap that has the fix, but isn't the most recent version (and won't cause backwards compability issues)?

**Comment by VasanthakumarTW** [comment]
Bootstrap date time picker version which we are using is really outdated (version 2- 2012). Latest version of it is Bootstrap 3 Date picker v4, and its is major update from bootstrap with lot of ui changes and parameter changes. As of now, we cannot upgrade it to latest without changing the Datetime picker fragments which wrapped on top if this library. Please advise on this.

**Comment by mogoodrich** [comment]
Okay, if that's what need to do I'm okay with it... is there a best practice for noting that we are using a patched version?  I'd worry that someone would inadvertently revert it without realizing it was a custom version.

I'm okay with this.  @mks-d  does this work for you?

**Pull request merged**
