### PR TITLE
RA-1592 :- Fix issue in merge patient page.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

1.fix on login page css and home page buttons.

This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by mozzy11** [comment]
@Akayeshmantha  , if possible it will be better if you could attach a screenshot before and after , for easy rebiewn . Otherwise good Job

**Comment by mozzy11** [comment]
@Akayeshmantha  , if possible it will be better if you could attach a screenshot before and after , for easy rebiewn . Otherwise good Job
cc @mks-d

**Comment by HerbertYiga** [comment]
you can attach these at the ticket Id @Akayeshmantha cc @mozzy11

**Comment by Akayeshmantha** [comment]
@mozzy11  I already attached fixes as videos in the chat thread.

Before :- 
https://drive.google.com/open?id=130ICvUEYu5Uc3b3ALsajRKgyvH0STSCB

After :- 
https://drive.google.com/file/d/1gb_hLYQv8JyQWOPC17A-eBvKTHebAmPe/view?usp=sharing

**Comment by Akayeshmantha** [comment]
@mks-d

**Comment by brandones** [comment]
Closing as stale.

**Pull request closed without merging**
