### PR TITLE
RA-1976: Referring to jQuery as $j does not work in the new UI

### PR DESCRIPTION
**Pull request by mogoodrich**

### CODE REVIEW

**Comment by mogoodrich** [comment]
This is a hack due to the case that we have referencing to jQuery using both "jq" ad "$j" littered throughout out code, but I don't think there would be any negative ramifications of doing this?

**Review by brandones — APPROVED** [review]
Yeah, there should be no problems. Thanks @mogoodrich .

**Review by mseaton — COMMENTED** [review]
I honestly don't know the implications of this - I think we need to be very careful about this.  Why exactly is this coming up now?  I think it would be better to just fix whatever is using $j to use jq where appropriate.

**Comment by mogoodrich** [comment]
@mseaton  I'd not sure why this is just coming up now (and only for the Peru form)... I will dig a little deeper but changing all the $j to jq seemed a bigger risk... in particular, I suspect that will break things on users of HFE and the 1.x UI.  I couldn't think of why my change would cause a problem unless someone was setting "$j" to something other than jquery elsewhere, or was setting it to a different version of jquery?

**Comment by brandones** [comment]
I mean, the fact that any piece of code is attempting to use jQuery via an abbreviation that it doesn't guarantee is defined is nuts—whether that abbreviation is `jq` or `$j` or even `$`. In the absence of the kind of technology that can load explicitly declared dependencies, mandating that everything assume only `jQuery` is defined is probably the least bad option. This just means adding lines like `const jq = jQuery` or `const $j = jQuery` at the top of the scripts that use them.

But really, there's no risk associated with this, unless we are doing the truly insane: monkey-patching functions into jQuery. I doubt that's happening, so there really shouldn't be any implications to worry about.

**Comment by brandones** [comment]
I guess the other thing that could go wrong is if there are multiple versions of jQuery. Like `jQuery`, `$j`, or `jq` refer to different versions of the library. You can check that by running `jQuery.fn.jquery` in the browser console, swapping out that first `jQuery` for the symbol that you want to check the referent library's version for.

**Comment by mogoodrich** [comment]
Updated comment coming...

**Comment by mogoodrich** [comment]
So I researched this a little more and there does seem a somewhat better place to add this, though I think it's crazy we got this far along without noticing this before... see my comment on the ticket (which I moved back into the HFE project):

https://issues.openmrs.org/browse/HTML-800

Testing now, will likely just merge if it works.

**Pull request closed without merging**
