### PR TITLE
Made changes to Fix EMPT 61 and EMPT171.

### PR DESCRIPTION
**Pull request by Parth59**
Hi,

This fix is an extended version of EMPT61 andI guess this also fixed EMPT 171.  Kindly review the same.
Also, here's the link for relevant details for EMPT61 :-  https://github.com/openmrs/openmrs-module-registrationapp/pull/110
 
For EMPT171 :-
Go to Register a Patient
--
Enter <SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT> in all the input fields in the form if client side validator allows it
Press Confirm from the left menu.

Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)

@isears

### CODE REVIEW

**Comment by HerbertYiga** [comment]
> RA-1875

can you add a correct link !!

**Comment by Parth59** [comment]
Apologies for the mistake. I have updated the correct link.

**Review by isears — APPROVED** [review]
Ok yeah looks like another case where our only option is to sanitize in the .js.

Thanks @Parth59 !

**Comment by Parth59** [comment]
Hi @ibacher , 

In order to resolve the issue, I  was trying to reproduce this issue at my end  after reverting the changes. While I was trying to enter the values in the Register a patient form from the image I was unable to add more than 3 numeric characters in the BirthDate field. 

Doubt



I am looking forward to your help in providing me the steps to mimic the issue at my end. Requesting your help at the earliest so that I can try my best to reach to an optimal solution.

Yours Sincerely,
Parth

**Comment by ibacher** [comment]
@Parth59 That’s right... the age field is restricted to numbers up to 120 and only numbers. The issue arose not from text I was trying to put in the field, but from an HTML element that’s added after the field text on the confirmation screen. I only entered the number “45” in the field you mention.

**Comment by Parth59** [comment]
Hi Team,
Kindly let's redirect our conversation to the following PR :- https://github.com/openmrs/openmrs-module-uicommons/pull/91

**Pull request merged**
