### PR TITLE
RA-1387:Upgrade FontAwesome from 3.x to latest (5+)

### PR DESCRIPTION
**Pull request by haripriya999**
# RA-1387:Upgrade FontAwesome from 3.x to latest (5+)

## Description of what I changed
Added space between icon and label

## Issue I worked on

see https://issues.openmrs.org/browse/RA-1387

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
I have tried running these changes but they make the icons look terribly worse. Cross check by building and conforming that you are actually running the uicommons module with these changes.

**Comment by haripriya999** [comment]
> I have tried running these changes but they make the icons look terribly worse. Cross check by building and conforming that you are actually running the uicommons module with these changes.

@dkayiwa  I updated the PR. Could you please take a look at it.

**Comment by dkayiwa** [comment]
Did you test your changes?

**Comment by haripriya999** [comment]
> Did you test your changes?

@dkayiwa  Yes, I did test them. They are working as expected.

**Comment by dkayiwa** [comment]
@haripriya999 why do many icons show empty boxes? An example is fa-couch

**Comment by haripriya999** [comment]
> @haripriya999 why do many icons show empty boxes? An example is fa-couch

@dkayiwa OpenMRS fetches icons from reference application module. You will see the icons after merging this PR: https://github.com/openmrs/openmrs-module-referenceapplication/pull/58

**Comment by dkayiwa** [comment]
Could you explain why some of the new icons are already displayed even before merging that pull request?

**Comment by haripriya999** [comment]
> Could you explain why some of the new icons are already displayed even before merging that pull request?
@dkayiwa  The icons which are being displayed were defined even before merging these changes.

**Pull request merged**
