### PR TITLE
WIP: UICM-6: Improve diagnosis icon

### PR DESCRIPTION
**Pull request by jayasanka-sack**
## Issue I worked on
see https://issues.openmrs.org/browse/UICM-6

## Description of what I changed
Change Password according to Michael Downey's suggestion on this mail thread:  https://groups.google.com/a/openmrs.org/d/msg/dev-refapp/BcbOiLXaUj0/CpEzvOReFSwJ

### Proposed icon :
Screenshot 2020-03-20 at 21 34 07

### CODE REVIEW

**Comment by brandones** [comment]
@dkayiwa @mogoodrich Who usually reviews this kind of stuff?

**Comment by mogoodrich** [comment]
Good question @brandones ... :)

**Comment by brandones** [comment]
🤦

**Comment by brandones** [comment]
I suggest we merge this, and if it freaks people out we can revert.

**Review by bmamlin — APPROVED** [review]
Looks much better!

**Pull request merged**
