### PR TITLE
Clarify comment on serverDate filter and add a console warning

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Review by mseaton — APPROVED** [review]
Looks fine to me.

**Review by mogoodrich — CHANGES_REQUESTED** [review]
As far as I remember, this function is working exactly as expected, but maybe it needed clearer documentation of the use case?

Use case: when you want to display the date/time based on the time on the server, not the client.  The assumption here is that the server timezone is the "facility" time and you want to display when something happened at the local time of the facility, and not convert it into whatever timezone the client machine happened to be set to.

We are in a bit of challenge now because we are looking to support the use case where the server time may not necessarily reflect the facility time, but in most legacy use cases this is correct.

**Comment by mogoodrich** [comment]
Following up to what I mentioned on the chat, I think what we need here is another method that strips off the time zone (and potentially the entire time component) but keeps the date in ISO format... (and then we use that method when we want to use the "server date" to instantiate a JavaScript Date object)

**Review by mogoodrich — APPROVED** [review]
LGTM...  getLocaleString might not fully meet the needs if you want to display in a specific time zone *but also* control the format specifically, but maybe there isn't much we can do about that.

**Pull request merged**
